<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [1]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can take matrix input from user or you can directly define the matrix and give input to the function
# reference for creating input - https://stackoverflow.com/questions/12293208/how-to-create-a-list-of-lists

# you can free to change all these codes/structure
# here A and B are list of lists

def matrix_mul(A, B):
    countA = 0
    countB = 0
    result  = [[0]*len(B[0])]*len(A)
    for i in range(len(A)):
        if A[i][1]:
            countA += 1

    for i in range(len(B)):
        if B:
            countB += 1

    if countA == countB:
        for i in range(len(A)):
            for j in range(len(B[0])):
                for k in range(len(A)):
                    result[i][j] += A[i][k]*B[k][j]

    return result

A = [[1,2],[3,4]]
B = [[1,2,3,4,5], [5,6,7,8,9]]
matrix_mul(A,B)

[[34, 44, 54, 64, 74], [34, 44, 54, 64, 74]]

In [2]:
import numpy as np
A   = [[1, 3, 4],
      [2, 5, 7],
      [5, 9, 6]]
B   = [[1, 0, 0],
      [0, 1, 0],
      [0, 0, 1]]
np.matmul(A,B)

array([[1, 3, 4],
       [2, 5, 7],
       [5, 9, 6]])

In [3]:
A = [[12, 7, 3],
	[4, 5, 6],
	[7, 8, 9]]


B = [[5, 8, 1, 2],
	[6, 7, 3, 0],
	[4, 5, 9, 1]]

result = [[0, 0, 0, 0],
		[0, 0, 0, 0],
		[0, 0, 0, 0]]
    
for i in range(len(A)):

# iterating by column by B

  for j in range(len(B[0])):

# iterating by rows of B

    for k in range(len(B)):

      result[i][j] += A[i][k] * B[k][j]

for r in result:
  print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [4]:
A = [[1, 2],
     [3, 4]]
B = [[1, 4],
    [5, 6],
    [7, 8],
    [9, 6]]

result =  [[sum(a*b for a, b in zip(A_row, B_col))
for B_col in zip(*B)]
for A_row in A ]
for r in result:
  print(r)



[11, 16]
[23, 36]


<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [5]:
import random
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

#video link for the topic - https://www.appliedaicourse.com/lecture/11/applied-machine-learning-online-course/2876/proportional-sampling/2/module-2-data-science-exploratory-data-analysis-and-data-visualization
# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    sum = 0
    cum_sum = [ ]
    for i in range(len(A)):
      sum = sum + A[i]
      cum_sum.append(sum)
    r = int(random.uniform(0, sum ))
    print(r)
    number = 0
    for index in range(len(cum_sum)):
       if(r>=cum_sum[index] and r<cum_sum[index+1]):
            return A[index+1]
    return number   #selected_random_number

def sampling_based_on_magnitued():
    a = dict()
    A = [1, 5, 27, 6, 13, 28, 100, 45, 10, 79]
    print(A, sum(A))

    for i in range(1,100):
        number = pick_a_number_from_list(A)
        if number not in a:
          a[number] = 1
        else:
          a[number] += 1
    print(a)
    print(number)
    
sampling_based_on_magnitued()

[1, 5, 27, 6, 13, 28, 100, 45, 10, 79] 314
35
307
141
109
293
137
106
196
172
301
32
5
45
218
265
190
183
279
178
41
232
183
32
282
34
74
151
84
95
2
294
312
146
205
243
291
276
261
204
166
56
17
265
102
240
235
109
176
47
18
27
293
114
126
134
159
0
24
38
209
256
97
88
297
105
100
12
289
216
73
257
120
178
120
98
3
167
26
224
225
272
202
283
44
104
195
5
86
25
274
167
293
298
263
47
260
48
243
245
{6: 3, 79: 29, 100: 30, 45: 12, 27: 9, 5: 4, 13: 6, 10: 2, 28: 3, 0: 1}
79


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [6]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# try to complete this question using regular expressions
# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    replacement = [("\D", "",), ("\d", "#"),]

    for olds, new in replacement:
      String = re.sub(olds, new, String)
      

    return String # modified string which is after replacing the # with digits
 
S1 = "234"
S2 = "a2b3c4" 
S3 = "abc" 
S4 = "2a$#b%c%561#"

print(replace_digits(S1))
print(replace_digits(S2))
print(replace_digits(S3))
print(replace_digits(S3))
print(replace_digits(S4))

###
###


####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [7]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
import math
# you can free to change all these codes/structure
def display_dash_board(marks, students):

    student_zip = list(zip(marks, students))

    student_zip.sort(key = lambda item : item[0])

    # write code for computing top top 5 students
    top_5_students = least_5_rankSudent = student_zip

    if len(student_zip)>5:
      top_5_students = student_zip[:-6:-1]
      # write code for computing top least 5 students
      least_5_students = student_zip[:5]
      # write code for computing top least 5 students
      
    students_within_25_and_75 = student_zip[math.ceil(0.25 * len(student_zip)):
                                                                     math.floor(0.75 * len(student_zip))]

      # students_within_25_and_75 = student_zip[math.ceil(0.25*len(student_zip):
      # math.flooar(0.75*len(student_zip))]

    return top_5_students, least_5_students, students_within_25_and_75

Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 

Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]

display_dash_board(Marks, Students)



([(98, 'student8'),
  (80, 'student10'),
  (78, 'student2'),
  (48, 'student5'),
  (47, 'student7')],
 [(12, 'student3'),
  (14, 'student4'),
  (22, 'student9'),
  (43, 'student6'),
  (45, 'student1')],
 [(43, 'student6'), (45, 'student1'), (47, 'student7'), (48, 'student5')])

In [8]:
#students_within_25_and_75
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 

Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80] 
for i in range(0,10):
  if Marks[i]>25 and Marks[i]<75:
    print(Students[i], Marks[i])
    print(i)


student1 45
0
student5 48
4
student6 43
5
student7 47
6


<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [9]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    closest_points_to_p = []
    final_list = [ ]
    for point in S:
      dnmtr =math.sqrt((point[0]**2) + (point[1]**2))*math.sqrt ((P[0]**2)+ (P[1]**2))
      nmrtr = point[0]*P[0]+point[1]*P[1]

      if dnmtr != 0:
          cosin_Distace_from_Point = math.acos(nmrtr/dnmtr)
          closest_points_to_p.append((cosin_Distace_from_Point, point))

    for item in sorted(closest_points_to_p, key= lambda x: x[0])[:5]:
      final_list.append(item[1])

    return final_list  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
closest_points_to_p = closest_points_to_p(S, P)
print("Closest point-cosine-distance - top 5:", *[point for point in closest_points_to_p], sep="\n") #print the returned values

Closest point-cosine-distance - top 5:
(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>

1.   List item
2.   List item


consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [10]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    red_point_tuple = -1
    
    if eval(line.replace('x', '*%s' % red[0][0]).replace('y', '*%s' % red[0][1])) > 0:
      red_point_tuple = 1
    
    for red_point in red:
      
      if red_point_tuple == 1 and eval(line.replace('x', '*%s' % red_point[0]).replace("y", "*%s" % red_point[1]))<0:
        
        return "on"

      if red_point_tuple == -1 and eval(line.replace("x", "*%s" % red_point[0]).replace("y", "*%s"
                                                                                        % red_point[1]))>0:
        return "on"

    blue_point_tuple = -1 * red_point_tuple

    for blue_point in blue:
      if blue_point_tuple == 1* eval(line.replace('x', "*%s" % blue_point[0]).replace("y", "*%s" % blue_point[1]))>0:
        return "on"
      
      if blue_point_tuple == -1 * eval(line.replace("x", "*%s" % blue_point[0]).replace("y", "*%s" % blue_point[1]))>0:
        return "on"

    return "yes"

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

yes
on
on
yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [11]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#run your code in the function for each of the inputs mentioned above and make sure that you get the same results

def curve_smoothing(string):
    empty_cell_list = []

    splitString =string.split(',')

    for idx in range(len(splitString)):
        if splitString[idx] != '_':
          empty_cell_list.append(idx)
    empty_cell_list.append(len(splitString) -1)

    print(empty_cell_list)

    [2, 6, 8]
    positionToStart = 0

    for element in empty_cell_list:
        cumulativeSumNextValue = int(splitString[element]) if splitString[element] != '_' else 0
       

        cumulativeSumNextValue += int(splitString[positionToStart]) if splitString[positionToStart] != '_' and positionToStart != element else 0

        integerReplaceEchaCells =  cumulativeSumNextValue //(element - positionToStart +1)

        splitString = [ integerReplaceEchaCells if positionToStart <= x <= element else splitString[x]
                       for x in range(len(splitString)) ]

        positionToStart = element


    return splitString #list of values
S1 = "80,_,_,_,_"
S2=  "_,_,30,_,_,_,50,_,_"
S3 = "40,_,_,_,60"
S4 = "_,_,_,24"
ans1 =smoothed_values= curve_smoothing(S1)
ans2 =smoothed_values= curve_smoothing(S2)
ans3 =smoothed_values= curve_smoothing(S3)
ans4 =smoothed_values= curve_smoothing(S4)
print(ans1) 
print(ans2)
print(ans3)
print(ans4)

[0, 4]
[2, 6, 8]
[0, 4, 4]
[3, 3]
[16, 16, 16, 16, 16]
[10, 10, 12, 12, 12, 12, 4, 4, 4]
[20, 20, 20, 20, 20]
[6, 6, 6, 6]




```
# This is formatted as code
```

<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [12]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings. Do not write 15 print statements.
# you can use nested loops or dictionaries to write your code

from fractions import Fraction
# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    intersection_s = dict()
    for item_list in A:
        dict_key = str(item_list[0]) + str(item_list[1])
        intersection_s[dict_key] = 0
    dictionary_s = {'S1':0, 'S2':0, 'S3':0}
    for i in range(len(A)):
      f_intersection_s_key = A[i][0]+A[i][1]
      intersection_s[f_intersection_s_key] += 1

      s_key = A[i][1]
      dictionary_s[s_key] += 1
     
    idx = 97
      
    print('{0:c}. P(F=F1|S==S1)={F1S1}/{S1}, P(F=F1|S==S2)={F1S2}/{S2}, P(F=F1|S==S3)={F1S3}/{S3}'.format(idx,
    F1S1=intersection_s.get('F1S1',0), S1=dictionary_s['S1'],F1S2=intersection_s.get(
    'F1S2',0), S2=dictionary_s['S2'],F1S3=intersection_s.get('F1S3',0), S3=dictionary_s['S3']))

    print('{0:c}. P(F=F2|S==S1)={F2S1}/{S1}, P(F=F2|S==S2)={F2S2}/{S2}, P(F=F2|S==S3)={F2S3}/{S3}'.format(idx+1,
    F2S1=intersection_s.get('F2S1',0), S1=dictionary_s['S1'],F2S2=intersection_s.get(
    'F2S2',0), S2=dictionary_s['S2'],F2S3=intersection_s.get('F2S3',0), S3=dictionary_s['S3']))

    print('{0:c}. P(F=F3|S==S1)={F3S1}/{S1}, P(F=F3|S==S2)={F3S2}/{S2}, P(F=F3|S==S3)={F3S3}/{S3}'.format(idx + 2,
    F3S1=intersection_s.get('F3S1',0), S1=dictionary_s['S1'],F3S2=intersection_s.get(
    'F3S2',0), S2=dictionary_s['S2'],F3S3=intersection_s.get('F3S3',0), S3=dictionary_s['S3']))

    print('{0:c}. P(F=F4|S==S1)={F4S1}/{S1}, P(F=F4|S==S2)={F4S2}/{S2}, P(F=F4|S==S3)={F4S3}/{S3}'.format(idx + 2,
    F4S1=intersection_s.get('F4S1',0), S1=dictionary_s['S1'],F4S2=intersection_s.get(
    'F4S2',0), S2=dictionary_s['S2'],F4S3=intersection_s.get('F4S3',0), S3=dictionary_s['S3']))

    print('{0:c}. P(F=F5|S==S1)={F5S1}/{S1}, P(F=F5|S==S2)={F5S2}/{S2}, P(F=F5|S==S3)={F5S3}/{S3}'.format(idx + 2,
    F5S1=intersection_s.get('F5S1',0), S1=dictionary_s['S1'],F5S2=intersection_s.get(
    'F5S2',0), S2=dictionary_s['S2'],F5S3=intersection_s.get('F5S3',0), S3=dictionary_s['S3']))


    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
c. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
c. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3


In [13]:
A = [['F1', 'S1'], ['F2', 'S2'], ['F3', 'S3'], ['F1', 'S2'], ['F2', 'S3'], ['F3', 'S2'], ['F2', 'S1'], ['F4', 'S1'], ['F4', 'S3'], ['F5', 'S1']]

dictionary1 = {'F1S1': 0,'F2S1': 0,'F3S1': 0,'F4S1': 0,'F5S1': 0,'F1S2': 0,'F2S2': 0,'F3S2': 0,
               'F4S2': 0,'F5S2': 0,'F1S3': 0,'F2S3': 0,'F3S3': 0,'F4S3': 0,'F5S3': 0,}

dictionary2 = {'S1': 0,'S2': 0,'S3': 0}

def compute_conditional_probabilites(A):
    for i in range(len(A)):
       k = A[i][0] + A[i][1]
       dictionary1[k] += 1
       dictionary2[A[i][1]] += 1

compute_conditional_probabilites(A)
print('Probability of P(F=F4|S==S3)', (dictionary1['F4S3']/dictionary2['S3']))

Probability of P(F=F4|S==S3) 0.3333333333333333


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [14]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
# you can free to change all these codes/structure
def string_diff(S1, S2):
    S1_set = list(set(S1.split()) - set(S2.split()))
    S2_set = [w1 for w1 in S1.split() if w1 not in S2.split()]
    print(f" Diffrent Words in S1 but not in S2 are : {S1_set}")
    print(f" Diffrent Words in S1 but not in S2 are : {S2_set}")

S1 = "the first column F will contain only 5 uniques values"
S2 = "the second column S will contain only 3 uniques values"
string_diff(S1, S2)


 Diffrent Words in S1 but not in S2 are : ['F', '5', 'first']
 Diffrent Words in S1 but not in S2 are : ['first', 'F', '5']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [15]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
from math import log
def compute_log_loss(A):
    cross_entropy = 0

    for row in A:
      cross_entropy += (row[0]* log(row[1], 10)+ ((1-row[0])*log(1- row[1], 10)))
    
    log_loss = -1 * cross_entropy/len(A)
  
    return log_loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
